CLASSES = [
    "mirror",
    "window",
    "cabinet",
    "table",
    "picture",
    "couch",
    "chair",
    "bed",
    "tv",
    "refrigerator",
    "sink",
    "curtain",
    "desk",
    "pillow",
    "bathtub",
    "window frame",
    "shelf",
    "armchair",
    "kitchen cabinet",
    "toilet",
    "stair",
    "microwave",
    "wardrobe",
    "towel",
    "lamp",
    "dishwasher",
    "oven",
    "washing machine",
    "rug",
    "fireplace",
    "blanket",
    "bathroom cabinet",
    "plant",
    "kitchen counter",
    "rack",
    "carpet",
    "dresser",
    "box",
    "clothes",
    "stove",
    "coffee table",
    "shower curtain",
    "book",
    "blinds",
    "sink cabinet",
    "shower cabin",
    "chest of drawers",
    "kitchen lower cabinet",
    "oven and stove",
    "kitchen island",
    "bag",
    "monitor",
    "pillar",
    "decorative plant",
    "bench",
    "dining table",
    "board",
    "stairs railing",
    "nightstand",
    "tv stand",
    "radiator",
    "basket",
    "bookshelf",
    "printer",
    "shelving",
    "hanging clothes",
    "vase",
    "hanger",
    "dining chair",
    "window curtain",
    "display cabinet",
    "heater",
    "washbasin",
    "ladder",
    "toy",
    "flower vase",
    "countertop",
    "sofa chair",
    "chest",
    "railing",
    "cloth",
    "clock",
    "office chair",
    "kitchen top",
    "speaker",
    "desk chair",
    "range hood",
    "drawer",
    "coffee machine",
    "closet",
    "table lamp",
    "cushion",
    "case",
    "stool",
    "boiler",
    "bathroom counter",
    "banister",
    "piano",
    "pouffe",
    "clutter",
    "ironing board",
    "appliance",
    "flowerpot",
    "bath cabinet",
    "air conditioner",
    "cardboard box",
    "furnace",
    "throw blanket",
    "bath towel",
    "calendar",
    "computer desk",
    "handrail",
    "screen",
    "electric box",
    "kitchen appliance",
    "window glass",
    "photo",
    "cooker",
    "lounge chair",
    "exercise equipment",
    "shower",
    "seat",
    "window shutter",
    "kitchen extractor",
    "staircase handrail",
    "parapet",
    "bathroom towel",
    "bathroom shelf",
    "kitchen table",
    "stovetop",
    "trashcan",
    "balustrade",
    "support beam",
    "refrigerator cabinet",
    "clothes dryer",
    "worktop",
    "bedside lamp",
    "bathrobe",
    "hat",
    "laundry basket",
    "mat",
    "ornament",
    "jacket",
    "storage shelving",
    "glass",
    "sofa seat",
    "shower-bath cabinet",
    "stand",
    "bar chair",
    "washer-dryer",
    "container",
    "bath sink",
    "book rack",
    "picture frame",
    "vacuum cleaner",
    "bed table",
    "tray",
    "storage cabinet",
    "pot",
    "bathtub platform",
    "treadmill",
    "sculpture",
    "rocking chair",
    "window shade",
    "grill",
    "mini fridge",
    "shower tub",
    "pool table",
    "kitchen cabinet lower",
    "stack of papers",
    "file cabinet",
    "electrical box",
    "sideboard",
    "sign",
    "plate",
    "whiteboard",
    "display table",
    "coat rack",
    "bouquet",
    "bicycle",
    "flag",
    "computer",
    "statue",
    "photo mount",
    "bottle",
    "wood",
    "footrest",
    "dinner table",
    "handbag",
    "paper",
    "bar",
    "cabinet table",
    "shade",
    "tool",
    "counter",
    "crib",
    "painting frame",
    "candle",
    "bucket",
    "amplifier",
    "bed comforter",
    "fire extinguisher",
    "washbasin counter",
    "crate",
    "bar cabinet",
    "electrical controller",
    "exercise bike",
    "desk lamp",
    "clothes rack",
    "locker",
    "cart",
    "canvas",
    "elevator",
    "bed curtain",
    "closet shelf",
    "lamp stand",
    "shower soap shelf",
    "umbrella",
    "plush toy",
    "decorative plate",
    "brochure",
    "bedframe",
    "duct",
    "laptop",
    "folding chair",
    "aquarium",
    "shower glass",
    "shower tap",
    "radio",
    "note",
    "arcade game",
    "patio chair",
    "water dispenser",
    "candle holder",
    "keyboard piano",
    "shower rail",
    "figure",
    "tank",
    "tree",
    "pile of magazines",
    "bulletin board",
    "antique clock",
    "balcony railing",
    "closet shelving",
    "dressing table",
    "shelf cubby",
    "headboard",
    "backrest",
    "decorative quilt",
    "paper storage",
    "office table",
    "laundry",
    "board game",
    "backpack",
    "handle",
    "kitchen shelf",
    "high shelf",
    "footstool",
    "lampshade",
    "freezer",
    "easy chair",
    "sunbed",
    "coat",
    "mantle",
    "shower bar",
    "clothing stand",
    "magazine",
    "scarf",
    "hammock",
    "hunting trophy",
    "record player",
    "cabinet clutter",
    "urinal",
    "cardboard",
    "spa bench",
    "spice rack",
    "archway",
    "antique telephone",
    "telescope",
    "jewelry box",
    "newspaper",
    "wine cabinet",
    "paper towel",
    "iron board",
    "binder",
    "storage",
    "firewood",
    "fuse box",
    "robe",
    "telephone",
    "island",
    "sofa set",
    "chimney",
    "hose",
    "barbecue",
    "massage bed",
    "stone support structure",
    "grass",
    "copier machine",
    "wreath",
    "water tank",
    "shower stall",
    "artwork",
    "cosmetics",
    "chest drawer",
    "globe",
    "curtain valence",
    "clothes bag",
    "gym equipment",
    "power breaker box",
    "kitchen sink",
    "jacuzzi",
    "jar",
    "sled",
    "gas furnace",
    "water fountain",
    "solarium",
    "exhibition panel",
    "sauna oven",
    "foot spa",
    "double armchair",
    "relief",
    "medical lamp",
    "tent",
    "plant ornament",
    "cradle",
    "dish rack",
    "foosball game table",
    "fish tank",
    "backsplash",
    "table stand",
    "soft chair",
    "exercise ladder",
    "gate",
    "stage",
    "folding table",
    "trampoline",
    "sleeping bag",
    "elephant sculpture",
    "book cabinet",
    "stereo set",
    "photo stand",
    "folding stand",
    "violin case",
    "round chair",
    "tile",
    "purse",
    "bunk bed",
    "sewing machine",
    "schedule",
    "shower dial",
    "light switch",
    "pantry",
    "mixer",
    "cutting board",
    "icebox",
    "hutch",
    "sheet",
    "sink table",
    "banner",
    "drawer sink table",
    "storage space",
    "bathroom accessory",
    "dish cabinet",
    "carpet roll",
    "dishrag",
    "cleaning clutter",
    "motorcycle",
    "staircase trim",
    "kitchen countertop items",
    "casket",
    "desk cabinet",
    "hook",
    "workstation",
    "swivel chair",
    "pool",
    "guitar frame",
    "baby changing station",
    "stack of stuff",
    "fence"
]